#Get JWT
POST http://localhost:5000/login
Content-Type: application/json

{"login": "admin", "password": "admin"}

###
POST http://localhost:5000/registration
Content-Type: application/json

{"name": "aaa","email": "000","login": "admin", "password": "admin"}
###
#Get JWT
POST http://localhost:5000/login
Content-Type: application/json

{"login": "tom", "password": "AH31LP#"}

###
POST http://localhost:5000/logout
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2OTQzNjIyMjJ9.NhfMJ21hm_ohLf6zZKe-WlRzuDajO3GnuhCIFsxeQPM

###
POST http://localhost:5000/meals
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2OTQzNjM0Njh9.TUM2zI1DsjZ3C8N-82NhI4bnXdRPfgqihGKUaiW6Ack

{"title": "TITLE FOR FIFTH USER", "description": "some desc", "ingredients": "", "weight": "100g", "price": "543"}
###

PUT http://localhost:5000/meals/7
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJleHAiOjE2OTQzNjQ3ODF9.BGQNMRL676o2OvuvVq_7JJ98Z0TE1sF7wOh8cC01uEE

{"title": "another title", "description": "some desc", "ingredients": "", "weight": "100g", "price": "543"}
###

GET http://localhost:5000/meals
Content-Type: application/json

###
GET http://localhost:5000/meals?&limit=10&offset=0&ordering=desc
Content-Type: application/json